# Generated by Django 3.2.13 on 2022-11-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20221130_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverage',
            name='user',
        ),
        migrations.AlterField(
            model_name='coverage',
            name='Coverage_strength',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='Status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='location_name',
            field=models.CharField(max_length=100),
        ),
    ]
