# Generated by Django 3.2.13 on 2022-11-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20221130_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverage',
            old_name='Coverage_strength',
            new_name='coverage_strength',
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='Status',
        ),
        migrations.AddField(
            model_name='coverage',
            name='status',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
